CACHE_MODE: False
DATASET:
  COCO_PANOPTIC_PATH: None
  COCO_PATH: ../datasets
  DATASET_FILE: cityscapes_to_bdd_daytime
  DA_MODE: uda
  NUM_CLASSES: 9
  REMOVE_DIFFICULT: False
DEVICE: cuda
DIST:
  DISTRIBUTED: True
  DIST_BACKEND: nccl
  DIST_URL: env://
  GPU: 0
  RANK: 0
  WORLD_SIZE: 4
EVAL: True

LOSS:
  AUX_LOSS: True
  BACKBONE_LOSS_COEF: 0.1
  BBOX_LOSS_COEF: 5.0
  CHANNEL_QUERY_LOSS_COEF: 1e-05
  CLS_LOSS_COEF: 2.0
  DA_GAMMA: 2
  DICE_LOSS_COEF: 1.0
  FOCAL_ALPHA: 0.25
  GIOU_LOSS_COEF: 2.0
  INSTANCE_QUERY_LOSS_COEF: 0.0001
  MASK_LOSS_COEF: 1.0
  SET_COST_BBOX: 5.0
  SET_COST_CLASS: 2.0
  SET_COST_GIOU: 2.0
  SPACE_QUERY_LOSS_COEF: 0.1
MODEL:
  BACKBONE: resnet50
  BACKBONE_ALIGN: False
  CHANNEL_ALIGN: False
  DEC_LAYERS: 6
  DEC_N_POINTS: 4
  DILATION: False
  DIM_FEEDFORWARD: 1024
  DROPOUT: 0.1
  ENC_LAYERS: 6
  ENC_N_POINTS: 4
  FROZEN_WEIGHTS: None
  HIDDEN_DIM: 256
  INSTANCE_ALIGN: False
  MASKS: False
  NHEADS: 8
  NUM_FEATURE_LEVELS: 4
  NUM_QUERIES: 300
  POSITION_EMBEDDING: sine
  POSITION_EMBEDDING_SCALE: 6.283185307179586
  SPACE_ALIGN: True
  TWO_STAGE: False
  WITH_BOX_REFINE: True
NUM_WORKERS: 2
OUTPUT_DIR: exps/r50_uda_c2b
RESUME: exps/r50_uda_c2fc/c2b_best_26.4_map.pth
SEED: 42
START_EPOCH: 0
TRAIN:
  BATCH_SIZE: 4
  CLIP_MAX_NORM: 0.1
  EPOCHS: 100
  LR: 0.0001
  LR_BACKBONE: 2e-05
  LR_BACKBONE_NAMES: ['backbone.0']
  LR_DROP: 35
  LR_DROP_EPOCHS: None
  LR_LINEAR_PROJ_MULT: 0.1
  LR_LINEAR_PROJ_NAMES: ['reference_points', 'sampling_offsets']
  SGD: False
  WEIGHT_DECAY: 0.0001

  #----DA Setting
da_backbone_loss_coef: 0.1
da_proto_loss_coef: 0.1
da_global_proto_coef: 0.1